name: AdvanceRespawn
main: net.scyllamc.matan.respawn.Main
version: 7.0.2
description: AdvanceRespawn
load: POSTWORLD
author: Matan Rak
softdepend: [Holograms,HolographicDisplays]
commands:
   AdvanceRespawn:
      description: main command for gta respawn
      aliases: [ar, respawn]